openapi.swaggerUI.rest.non_entity:
  path: '/admin/config/services/openapi/swagger-ui/rest/non-entity'
  defaults:
    _controller: '\Drupal\openapi_docs\Controller\SwaggerUIController::nonEntityResources'
  methods: [GET]
  requirements:
    _permission: 'access openapi api docs'

openapi.swaggerUI.rest.bundle:
  path: '/admin/config/services/openapi/swagger-ui/rest/{entity_type}/{bundle_name}'
  defaults:
    _controller: '\Drupal\openapi_docs\Controller\SwaggerUIController::bundleResource'
  methods: [GET]
  requirements:
    _permission: 'access openapi api docs'


openapi.swaggerUI.rest.list:
  path: '/admin/config/services/openapi/swagger-ui/rest/list-resources'
  defaults:
    _controller: '\Drupal\openapi_docs\Controller\SwaggerUIController::listResources'
    _title: 'REST API'
  methods: [GET]
  requirements:
    _permission: 'access openapi api docs'

openapi.swaggerUI.jsonapi:
  path: '/admin/config/services/openapi/swagger-ui/jsonapi'
  defaults:
    _controller: '\Drupal\openapi_docs\Controller\SwaggerUIController::openApiResources'
  methods: [GET]
  requirements:
    _permission: 'access openapi api docs'

