openapi.list:
  title: REST API
  description: 'REST API documentation.'
  parent: system.admin_config_services
  route_name: openapi.swaggerUI.rest.list

openapi.jsonapi:
  title: JSON Api Documentation
  description: 'JSON API documentation.'
  parent: system.admin_config_services
  route_name: openapi.swaggerUI.jsonapi
  class: Drupal\openapi_docs\Plugin\Menu\DocMenuLink
